### ISSUE TITLE
Please add a license.

### ISSUE THREAD

**Issue by Poikilos** [shybovycha/irrPaint3D#1]
I described at <https://stackoverflow.com/questions/8803917/realtime-object-painting> that the repo is missing a license but mentioned the wrong repo (moo3d) when I asked on LinkedIn so I am posting the issue here to ensure the request is clear. However, feel free to add one there too since you wrote in the readme that you intended for the program to be the start of a "free" program.

Having something posted online without a license defaults to the most restrictive application of copyright: <https://choosealicense.com/no-permission/>. Suggestion: Add GPLv2.1 to match Minetest since that is one of few (or the one?) maintained game(s) using Irrlicht still and this program may become a good editor for models for Minetest. Otherwise an MIT License is compatible with GPL at least (as an upstream source).

The easy way is:
- Log into GitHub, go to <https://github.com/shybovycha/irrPaint3D>
- Add File, Create New File
  - Change the name to license.txt and GitHub's license chooser button will appear:
    - Click the "Choose a license template" button that appeared on the right then choose the one you want and add your name and 2012 if not autofilled.
  - Change the branch to (commit directly to) "master" at the bottom.
  - Click "Commit new file" 

Thank you.

**Comment by shybovycha** [comment]
I have no problems doing that. Just curious (it is not 100% clear from your message): why do you need that?

**Comment by Poikilos** [comment]
Hi, I'm so glad you got back to me. I'm working on many mobs for Minetest, and using Blender causes the brush to overlap on the next polygon. When there is no space between UV islands, the color spills onto a random polygon. Many of the mobs in Minetest were unwrapped with no attention to detail, apparently just pushing the unwrap button (very rarely even setting space between islands). I would like to improve your program if necessary, possibly adding custom rounding to avoid the issues above, if it doesn't need modifications that's fine too. However, I want the license to be free and clear in case I want to give the program or my fork to other Minetest modders, perhaps even packaged for a particular distro. I am familiar enough with Irrlicht to improve the software if necessary. Thanks.

**Comment by shybovycha** [comment]
Oh, I see it now. Thanks for sharing.

Few days ago I was thinking about revising this repo, actually - using vcpkg, CMake and refactoring the code.

On the algorithmic note, not sure if I implemented it that way, but it's best to use the inverse matrix (view * model) and just multiply it by the matrix obtained from the intersection point (from triangle selector). I think after reading the question on StackOverflow that was one of tbe suggested answers, but back in the day I was not smart enough to understand all those matrix transformations and how they apply to 3D graphics (LOL).

**Comment by Poikilos** [comment]
I'd like to get in touch about the build system and plans since I'm likely to make big improvements and features helpful for Minetest. 1. Thanks for the FOSS. 2. Are you looking for a dependency processor for a program that only has one dependency? I'm not sure what you're getting at. If you want to allow users to build in Windows easily, you can use cmake, which can generate Code::Blocks or Visual Studio projects. 3. Can you get in touch with me at <https://expertmultimedia.com/index.php?htmlref=contact.html> since neither of us publish our e-mail addresses? We can get in touch in IRC or Discord since that may be better for this.

**Comment by shybovycha** [comment]
For the build system see #3 - it is aupposed to be CMake indeed woth vcpkg to pull the dependencies, since CMake alone is rather pain in the neck to use with dependencies otherwise. I shall get back to it next week, since it is a long weekend in Australia.

Re. having faster discussion, try looking me up on Discord by `moofoo`. Or we can continue discussion here 😋

**Comment by Poikilos** [comment]
Ok, I'm not able to find you or add friend on Discord without the digits. My full username with the digits is: `@Poikilos#9328` Invite: https://discord.gg/69ht6grj

**Comment by Poikilos** [comment]
I'm also on IRC network irc.minetest.org
